### PR TITLE
Code climate badge for code score

### PR DESCRIPTION
**Pull request by garrypolley**
This is an interesting metric and I think it could help keep the code in a better state over time. It exists on some other repos and I figured we may as well try it here.

### CODE REVIEW

**Comment by acharlieh** [comment]
:+1: I think we should consider fixing #57 and show how terrible test coverage there currently is on this thing too. While we're at it we could also consider adding other http://shields.io/ as well (version from supermarket might be useful)

**Comment by garrypolley** [comment]
It'd be good to add the released version that is out as well.  I'm not seeing a simple way to add a released version that does not involve manual updates.  I'd prefer to have a service or something that did it automatically.

**Comment by garrypolley** [comment]
I figured out how to get the version on the readme.  Badges seem to be on the rise: 

http://badge.fury.io/for/gh/cerner/cerner_splunk

There is actually an entire repo dedicated to proper badges: 

https://github.com/badges/shields

Which is the site you linked, and it has other sets of sites linked there.

**Comment by acharlieh** [comment]
Added the webhook as mentioned in the badge fury site. Going to merge with the green button since it's a doc only change.

**Pull request merged**
