### PR TITLE
Clean up Vagrant Artifacts

### PR DESCRIPTION
**Pull request by acharlieh**
Leading into #60, I just wanted to start with some cleanup of the Vagrant artifacts and documentation. 

Highlights: 
* Removal of the Chef 10 test box and related artifacts
* Removal of detection of Cerner network (and attempts to pull internal resources)
* Ensuring ChefDK is always the latest version (on a new provisioning of the chef image)

As this is all test code, I also propose no cookbook version increment upon merge. (please +/-1 this as well as the PR contents)

### CODE REVIEW

**Comment by BobbyRyterski** [comment]
:+1:

**Comment by acharlieh** [comment]
The travis failures are all completely unrelated (rubocop updates), I'll send a different PR for them. (as that will impact cookbook code, thus need a version increment).

**Comment by nimeshsubramanian** [comment]
:+1:

**Comment by david-crowder** [comment]
+1

**Comment by Pi-Po** [comment]
I got here by accident. If I can contribute in some way, let me know. Best regards, Jose. From Cercedilla, a remote village in Spain.

**Comment by acharlieh** [comment]
Welcome @Pi-Po. You should know that Github is social and everyone is welcome to download and use the project we are developing here, subject to the terms of the Apache License, Version 2.0. 
If you feel there are improvements that could be made, everyone is welcome to submit issues and pull requests for consideration. If you choose to do so, we ask that you observe our [guide to contributing](https://github.com/cerner/cerner_splunk/blob/stable/CONTRIBUTING.md). 

You should also know that this project is owned by a business, Cerner Innovations, Inc. therefore, by submitting an contribution you would be implicitly granting certain licenses around your contribution to Cerner.  
We're working through the exact verbiage of external contribution licensing with our legal folks currently (and will update our Contributing doc as soon as it is done), but I suspect it'll be similar to grants under Contributor Licensing Agreements found at other companies.

For a few examples of what it may look like, check out the descriptions of CLAs for:
* [Chef](https://docs.chef.io/community_contributions.html#about-clas-and-cclas)
* [Microsoft](http://azure.github.io/guidelines.html#cla)
* [Splunk](http://www.splunk.com/goto/individualcontributions) 

Thanks for your interest!

**Pull request merged**
