### PR TITLE
Fixes #56 - Add License Master Vagrant Image

### LINKED ISSUE #56: Add License Master Vagrant Image
There's a perpetual 1MB license [available in the java SDK](https://github.com/splunk/splunk-sdk-java/blob/94894b1c63a2388aed097e96c0253585f474c1ae/tests/com/splunk/splunk.license) we should use this to have a license master Vagrant image

### PR DESCRIPTION
**Pull request by acharlieh**
Fixes #56 by adding a License Master VM (not configured to be used by the other nodes)

Other changes I made in the process of getting this to work.
* I switched to the [xml cookbook](https://github.com/opscode-cookbooks/xml) for installing the nokogiri gem (since it was having trouble installing the latest version, and it seemed silly to duplicate work there). * For consistency I then decided to install the chef-vault gem with the [chef-vault cookbook](https://github.com/opscode-cookbooks/chef-vault) and thus obsolete #49 (since both chef_gem installations are now handled by other cookbooks).
* I switched the upload of the vagrant repo to be simply knife upload, but this required switching from .rb files to .json files. (which are very similar), and updated to ChefDK 0.4.0 in the process

### CODE REVIEW

**Comment by david-crowder** [comment]
+1

**Comment by nimeshsubramanian** [comment]
+1

**Comment by acharlieh** [comment]
Question for the group... This feels like it should be merged with an incremented minor version. +/-1?

**Comment by aaronblythe** [comment]
+1 for the change
+1 for bumping the minor version

**Comment by ncerny** [comment]
+1

I agree that this should be a minor change.

**Pull request merged**
