### PR TITLE
Fixes #94. Fixes #70. Updates for LWRP changes

### LINKED ISSUE #70: Chef 13 warning, need to declare resource name for splunk_app
Noticed this in cerner_splunk today. We probably should fix this:

```
WARN: Class Chef::Provider::SplunkApp does not declare 'resource_name :splunk_app'.
WARN: This will no longer work in Chef 13: you must use 'resource_name' to provide DSL.
```

### LINKED ISSUE #94: Chef Client 12.5.1 issues with  splunk_forwarder_monitors provider
When upgrading from Chef client 12.4.3 -> 12.5.1 I started to get failures configuring my splunk forwarder monitors (errors below).  Please let me know if there is a change need in this cookbook or how I am using to resolve this issue.

```
splunk_forwarder_monitors[my_service] action install[2015-10-09T12:36:40-05:00] WARN: Using an LWRP provider by its name (CernerSplunkForwarderMonitors) directly is no longer supported in Chef 12 and will be removed. Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-10-09T12:36:40-05:00] WARN: Class Chef::Provider::CernerSplunkForwarderMonitors does not declare 'resource_name :cerner_splunk_forwarder_monitors'.
[2015-10-09T12:36:40-05:00] WARN: This will no longer work in Chef 13: you must use 'resource_name' to provide DSL.
 (up to date)
splunk_app[my_service] action create[2015-10-09T12:36:40-05:00] WARN: Class Chef::Provider::SplunkApp does not declare 'resource_name :splunk_app'.
[2015-10-09T12:36:40-05:00] WARN: This will no longer work in Chef 13: you must use 'resource_name' to provide DSL.
```

```
splunk_forwarder_monitors[my_service] action install  
==============================================================================  
Error executing action `install` on resource 'splunk_forwarder_monitors[my_service]'  
===============================================================================
    Chef::Exceptions::ProviderNotFound  
    ----------------------------------  
    Cannot find a provider for splunk_forwarder_monitors[my_service] on redhat version 6.6
```

### PR DESCRIPTION
**Pull request by jdmurphy**
Updated LWRP for Chef 12.5 breaking splunk_forwarder_monitors and updated to fix Chef 13 warnings.

### CODE REVIEW

**Comment by garrypolley** [comment]
:+1:

**Comment by gravesb** [comment]
+1

**Comment by gravesb** [comment]
From one of the comments on #94, @acharlieh noted this commit: https://github.com/acharlieh/cerner_splunk/commit/3e39177b5ddaecd0bc3d5255e79068ad89c073da

I'm thinking this should also include the changes to the test recipe in that commit to cover both ways to call the forwarder lwrp.

**Comment by acharlieh** [comment]
+1 to the contents of the changes here.
+1 to @gravesb comment on updating the test recipe.

One additional ask, could you squash down to fewer commits and force push your branch to update? I think that history would be much cleaner if this is in 3 commits: 
* Update berkshelf version and dependencies. (Extended message could link issues and details)
* Remove resource_name in favor of provides for Chef 12.5 (Extended commit message could go into files and details, but that's what a diff is for)
* Add test recipe resources to verify working of alternate names for LWRP (Could talk about versions of Chef that this works on and why in extended message).

**Comment by acharlieh** [comment]
Additionally upon merge, are you proposing that this is a minor version increment or a fix version increment?

**Comment by jdmurphy** [comment]
I can squash some of this down, yes. 

I am truthfully on the fence about whether it should be a patch level increment or minor version increment because of the amount of changes which had to be done to get certain parts up to date. I could go either way.

**Comment by alecxvs** [comment]
+1

**Comment by acharlieh** [comment]
:+1: 

I think I've talked myself into minor version increment, noting that the addition of alternate names for the LWRP is a new passively added feature. It happens to have a fix as well which was the origin of how we got down that path, but functionally it feels like a minor version.

**Comment by maximusfloydus** [comment]
When do you plan a release of 1.13?

**Comment by acharlieh** [comment]
@maximusfloydus So we actually had an issue logged internally that never made it out here #96 that I was hoping that we'd be able to get in before tagging, but conversations on it with Splunk Support have pushed as they're re-tooling their support teams. 

So the question becomes, what are your needs for a tagged version?

**Comment by maximusfloydus** [comment]
It is not urgent as it isn't blocking me.  I was getting a bunch of
cookbook releases ready and wanted to do some planning.

**Pull request merged**
