### PR TITLE
Allow convenient specification of volumes for index storage locations

### PR DESCRIPTION
**Pull request by gravesb**
This allows a convenient way to specify the base volume for a given index.  Otherwise you would have to specify the coldPath and homePath for each index individually within the indexes data bag.  I originally considered putting the volume within the config/\<index_name\> location but then that hash would no longer match the raw indexes.conf stanza anymore.  So I opted to put it in the flags, although I know those were originally meant to be boolean only.  I'm open to suggestion on a better place to put the volume specification for an index in the data bag if you want to keep flags as only boolean attributes.

### CODE REVIEW

**Comment by acharlieh** [comment]
Yeah, the idea of flags was to keep config part close to indexes.conf, but in hindsight, I wonder if it would have been better to just prefix all "flag" fields as "_" so that way their configurations would be inline with everything else (and not have two parts of a data bag to look at... ). If we want to start this with the volume setting, I'd be down with that :) )

**Comment by acharlieh** [comment]
Two other things that we may want to consider for configurability of indexes.conf... 
1) a flag for specifying the on-disk name for an index... this might be useful for if people may want to rename indexes, but also for being able to easily use the volume specification. Additionally for built in splunk indexes (e.g. _internal, main, _audit) who for legacy reasons use on disk names different from their index names (e.g. _internaldb, defaultdb, audit). (we could default this to the name of the index of course).
2) additionally managing the `tstatsHomePath` parameter... by default this is set for any new index to `volume:_splunk_summaries/$_index_name/datamodel_summary` which maps by default to $SPLUNK_DB, but if we're relocating indexes to alternate volumes, I think we'd also want to relocate datamodel summaries as well?

**Comment by gravesb** [comment]
I have all the suggested changes updated on the PR, although it looks like ruby 1.9.3 doesn't like my custom chefspec matcher :(

**Comment by gravesb** [comment]
Fixed the custom chefspec matcher to work with both Chef 11 and Chef 12 and rebased on stable to include the rubocop fixes. The builds are all passing now for this branch.

**Comment by jdmurphy** [comment]
+1

**Comment by alecxvs** [comment]
+1

**Pull request merged**
